SET character_set_client = utf8;
SET NAMES utf8;
--- Очистка базы перед сборкой дистрибутива
DELETE FROM `ib_access` WHERE `fid`!=0;
UPDATE `ib_bots` SET `last_visit`=0;
TRUNCATE `ib_banned_ip`;
TRUNCATE `ib_captcha`;
TRUNCATE `ib_category`;
TRUNCATE `ib_complain`;
UPDATE `ib_crontab` SET nextrun=0;
TRUNCATE `ib_file`;
TRUNCATE `ib_forum`;
TRUNCATE `ib_last_visit`;
TRUNCATE `ib_log_action`;
TRUNCATE `ib_mark_all`;
TRUNCATE `ib_moderator`;
TRUNCATE `ib_online`;
TRUNCATE `ib_poll`;
TRUNCATE `ib_poll_variant`;
TRUNCATE `ib_post`;
TRUNCATE `ib_file`;
TRUNCATE `ib_privmsg_link`;
TRUNCATE `ib_privmsg_post`;
TRUNCATE `ib_privmsg_thread`;
TRUNCATE `ib_privmsg_thread_user`;
TRUNCATE `ib_rating`;
TRUNCATE `ib_relation`;
TRUNCATE `ib_search`;
TRUNCATE `ib_search_result`;
TRUNCATE `ib_tagentry`;
TRUNCATE `ib_tagname`;
TRUNCATE `ib_text`;
TRUNCATE `ib_timeout`;
TRUNCATE `ib_topic`;
DELETE FROM `ib_user` WHERE `id`>3;
TRUNCATE `ib_user_contact`;
DELETE FROM `ib_user_ext` WHERE `id`>3;
ALTER TABLE `ib_user` AUTO_INCREMENT=4;
DELETE FROM `ib_user_settings` WHERE `id`>3;
TRUNCATE `ib_user_field`;
TRUNCATE `ib_user_value`;
TRUNCATE `ib_user_award`;
TRUNCATE `ib_user_warning`;
TRUNCATE `ib_views`;
TRUNCATE `ib_vote`;
INSERT INTO `ib_forum` (`id`,`module`,`title`,`descr`,`hurl`,`category_id`,`parent_id`,`sortfield`,`lastmod`,`last_post_id`,`icon_new`,`icon_nonew`) VALUES ('1','statpage','О проекте','Информация о нашем сайте','about',0,0,1,0,0,'','');
INSERT INTO `ib_text` (`id`, `type`, `data`) VALUES (0, 0, 'Правила форума разрабатываются. А пока просим придерживаться общих принципов вежливости и доброжелательности.');
INSERT INTO `ib_text` (`id`, `type`, `data`) VALUES (1, 2, 'Если вы читаете этот текст, то установка Intellect Board прошла успешно. \r\nВ дальнейшем его можно будет заменить на информацию о вашем проекте или просто удалить.\r\nЭтот раздел имеет тип "Статическая страница". Обычный раздел с темами и соощениями вы можете \r\nсоздать в Центре Администрирования.');
